### ISSUE TITLE
Steam Achievements icon missing

### ISSUE THREAD

**Issue by PolarizedIons** [Ellpeck/FoeFrenzyIssues#9] opened 2019-11-15 20:28 UTC
**Describe the issue**
The icons for the steam achievements are missing

**To Reproduce**
Steps to reproduce:
1. Get an achievement
2. Go to the "activity" page under your username

**Expected behavior**
The icons to be there

**Crash Report**
none

**Screenshots**
![image](https://user-images.githubusercontent.com/4587682/68973547-3d996100-07f7-11ea-8717-80fcee070701.png)

**Game Info**
 - Operating System: Arch Linux
 - Game Version: N/A

**Comment by Ellpeck** [comment] 2019-11-15 20:35
I'm getting that issue too, but for me, they *do* work in the game's Library entry on the right. If that's the case for you too, you can close this issue as it's probably caused by the game not being released yet, and the assets not syncing across Steam properly.
![Steam_2019-11-15_21-34-50](https://user-images.githubusercontent.com/5741138/68973936-c4e2d680-07ef-11ea-902d-f63e3c74f13d.png)

**Closed** 2019-11-17 09:17 UTC
